# Site settings
title:       '"I think it might work"'
email:       tyler@tylerstroud.com
author:      Tyler Stroud
description: "Software Engineer"
baseurl:     ""
url:         "http://tylerstroud.com"

# Google analytics
google_analytics: true

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: tystr
twitter_username: tylerstroud
google_plus_id:
linkedin_username: tylerstroud
bitcoin_url:
paypal_url:
flattr_button:
#flattr_button: "<script id='fbv63ao'>(function(i){var f,s=document.getElementById(i);f=document.createElement('iframe');f.src='//api.flattr.com/button/view/?uid=tystr&button=compact&url='+encodeURIComponent(document.URL);f.title='Flattr';f.height=20;f.width=110;f.style.borderWidth=0;s.parentNode.insertBefore(f,s);})('fbv63ao');</script>"

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
